apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aws-iot-greengrass.fullname" . }}
  labels:
  {{- include "aws-iot-greengrass.labels" . | nindent 4 }}
data:
  config.yaml: |
    system:
      certificateFilePath: {{ .Values.greengrass.certificateFilePath | quote }}
      privateKeyPath: {{ .Values.greengrass.privateKeyPath | quote }}
      rootCaPath: {{ .Values.greengrass.rootCaPath | quote }}
      rootpath: {{ .Values.greengrass.rootpath | quote }}
      thingName: {{ .Values.greengrass.thingName | quote }}
    services:
      aws.greengrass.Nucleus:
        componentType: "NUCLEUS"
        version: {{ .Values.image.tag | default .Chart.AppVersion | quote }}
        configuration:
          awsRegion: {{ .Values.greengrass.awsRegion | quote }}
          iotRoleAlias: {{ .Values.greengrass.iotRoleAlias | quote }}
          # TODO verify
          iotDataEndpoint: "{{ .Values.greengrass.awsPrefix}}-ats.iot.{{ .Values.greengrass.awsRegion | quote }}.amazonaws.com"
          iotCredEndpoint: "{{ .Values.greengrass.awsPrefix }}.credentials.{{ .Values.greengrass.awsRegion | quote }}.amazonaws.com"
    {{ toYaml .Values.greengrass.nucleusConfiguration | nindent 10 }}
