{{- if .Values.service.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-iot-greengrass.fullname" . }}
  labels:
  {{- include "aws-iot-greengrass.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .containerPort }}
      {{- with .protocol }}
      protocol: {{ . | quote }}
      {{- end }}
      {{- with .name }}
      name: {{ . | quote }}
  {{- end }}
  {{- end }}
  selector:
  {{- include "aws-iot-greengrass.selectorLabels" . | nindent 4 }}
  {{- end }}
