apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-iot-greengrass.fullname" . }}
  labels:
  {{- include "aws-iot-greengrass.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8883
      protocol: TCP
      name: mqtt
  selector:
  {{- include "aws-iot-greengrass.selectorLabels" . | nindent 4 }}
